# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Registry output
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      run:  echo "$REGISTRY_URL"
    - name: Build with Maven
      run: mvn install --no-transfer-progress -f ./pom.xml -pl common -am
      
    - name: Build operator with Maven
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      run: mvn clean package --no-transfer-progress -f ./operator/pom.xml -Doperator -Dquarkus.container-image.build=true -Dquarkus.container-image.username="$env:REGISTRY_USER" -Dquarkus.container-image.password="$env:REGISTRY_PASS" -Dquarkus.container-image.registry="$env:REGISTRY_URL" -Dquarkus.container-image.name=keycloak-operator -Dquarkus.container-image.group="keycloak" -Dquarkus.jib.platforms="linux/amd64,linux/arm64" -Dquarkus.container-image.push=true     
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
